In [42]:
import numpy as np
a = np.array ([[2,7,3], [8,5,4]])
print(a)

[[2 7 3]
 [8 5 4]]


In [43]:
import numpy as np
a = np.array ([[5, 3], [2, 3]])
b = np.array ([[1, 3], [7, 3]])
print(a * b)

[[ 5  9]
 [14  9]]


In [44]:
import numpy as np
a = np.array ([[5, 3],
              [2, 3]])
b = np.array ([[1, 3],
              [1, 3]])
produit = np.dot (a, b)
print(produit)

[[ 8 24]
 [ 5 15]]


In [45]:
import numpy as np
a = np.array ([[5, 3], [2, 3]])
print(a.T)

[[5 2]
 [3 3]]


In [46]:
import numpy as np
a = np.eye (3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
import numpy as np
m = np.linspace (0, 20, 5)
print("La matrice obtenue à partir de l'intervalle [0 , 20]  est:", m)
# La sortie est:
# La matrice obtenue à l'étape 5 est: [0. 5. 10. 15. 15. 20.]

La matrice obtenue à partir de l'intervalle [0 , 20]  est: [ 0.  5. 10. 15. 20.]


In [48]:
import numpy as np
a = np.arange(5 , 20 , 3 , int)
print(a)
# renvoie une matrice d'entiers : [ 5  8 11 14 17]

[ 5  8 11 14 17]


In [49]:
import numpy as np
a = np.arange(0 , 1 , 0.1 , float)
print(a)
# renvoie la matrice formée de nombres  réels : [0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [50]:
# coding: utf-8
import numpy as np
a = np.arange(0 , 11, 2 , int).reshape(2 , 3)
b = a.reshape(3 , 2)
print(a)
print(b)
# print(a) renvoie la matrice formée de nombres  entiers : [[ 0  2  4]  [ 6  8 10]]
# print(b) renvoie la matrice formée de nombres  entiers : [[ 0  2] [ 4  6] [ 8 10]]

[[ 0  2  4]
 [ 6  8 10]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [51]:
# coding: utf-8
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4, 5])

# concaténation de a et b
c = np.concatenate((a, b))
print("La matrice obtenue en concaténant a et b est : c = " , c) 
# La matrice obtenue en concaténant a et b est : c =  [1 2 3 4 5]

La matrice obtenue en concaténant a et b est : c =  [1 2 3 4 5]


In [52]:
import numpy as np
x = np.linspace (0, 3,4)
y = np.exp (x)
print(y)
# La sortie est: [1. 2.71828183 7.3890561 20.08553692]

[ 1.          2.71828183  7.3890561  20.08553692]


In [53]:
import numpy as np
a = np.array ([[2, 1],
              [5, 3]])
b = np.linalg.inv (a)
print ("L'inverse matriciel de a est:", b)

L'inverse matriciel de a est: [[ 3. -1.]
 [-5.  2.]]


In [54]:
import numpy as np
a = np.array ([[1, 2],
              [3, 2]])
valPropres = np.linalg.eigvals (a)
print ("Les valeurs propres de la matrice a sont:", valPropres)
# La sortie est: Les valeurs propres de la matrice a sont: [-1. 4.]

Les valeurs propres de la matrice a sont: [-1.  4.]
